export { default as Home } from './Home/Home';
export { default as DetailMoviePage } from './DetailPage/DetailMoviePage';
export { default as DetailTvPage } from './DetailPage/DetailTvPage';
export { default as LoadMore } from './LoadMore/LoadMore';
export { default as MoviePage } from './MoviePage/MoviePage';
export { default as TVPage } from './TVPage/TVPage';
export { default as SearchPage } from './SearchPage/SearchPage';
export { default as DiscoverPage } from './DiscoverPage/DiscoverPage';
export { default as PersonPage } from './PersonPage/PersonPage';
